version: '3'

services:
    app:
        image: node:16-alpine
        command: tail -f /dev/null
        container_name: COMPOSE_PROJECT_NAME_app
        environment:
            VIRTUAL_HOST: $COMPOSE_PROJECT_NAME-app.local
        volumes:
            - '.:/var/www'
        working_dir: /var/www
        network_mode: bridge
