version: '3'

services:
    app:
        image: node:16-alpine
        container_name: COMPOSE_PROJECT_NAME_app
        environment:
            VIRTUAL_HOST: $COMPOSE_PROJECT_NAME-app.local
        volumes:
            - '.:/app'
        working_dir: /app
        network_mode: bridge
